### DISCUSSION TITLE
Migliorie test CD/CI

### DISCUSSION THREAD

**Discussion by zerai** [iisgiua/giuaschool#239] [Idee e proposte]
Discussione per eventuali migliorie da apportare ai test e alla pipeline su GHA.

- Attualmente occorre circa 1 ora e 50 min. per completare i test su GHA, sarebbe il caso di provare a ridurre il tempo,
  in termini di CD/CI un fast feedback è un requisito essenziale.

- Migliorare la percentuale di coverage, allo stato attuale risulta al 10% (badge nel readme file).

Altro?

**Comment by zerai** [comment]
@trinko  Attualmente la CI si attiva esclusivamente al push sul branch master, sarebbe possibile attivarla anche per le PR?

**Reply by trinko** [reply]
> @trinko Attualmente la CI si attiva esclusivamente al push sul branch master, sarebbe possibile attivarla anche per le PR?

Ho modificato gli script per attivare i test sulle PR. Dovrebbe funzionare correttamente.

**Reply by zerai** [reply]
Grazie!! ho verificato facendo un PR minimale..
Almeno ora eventuali errori nella CI emergono prima del merge sul master.

**Comment by zerai** [comment]
Possibili migliorie al workflow test-deploy.yml

Nel job 'test-phpunit' viene eseguito il build di 3 immagini ma nei successivi step ne viene usata solo 1 quella di test
```yml
      - name: Build docker images
        run: |
          docker build -t "gs:prod" -f tests/docker/Dockerfile .
          docker build -t "gs:dev" --build-arg BASE_IMAGE=gs:prod -f tests/docker/DockerfileDev .
          docker build -t "gs:test" --build-arg BASE_IMAGE=gs:dev -f tests/docker/DockerfileTest .
      - name: Run phpunit
        run: |
          docker run --name "gs_test" --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 gs:test tests/docker/test-phpunit.sh
          docker cp gs_test:/var/www/giuaschool/clover.xml clover.xml

```
questi 2 comandi di build si potrebbero eliminare dal job per ridurne il tempo. 
```yml
          docker build -t "gs:prod" -f tests/docker/Dockerfile .
          docker build -t "gs:dev" --build-arg BASE_IMAGE=gs:prod -f tests/docker/DockerfileDev .
```

Stessa cosa per il job 'test-behat'  (viene ciclato 17 volte)

 build di 3 immagini ma nei successivi step ne viene usata solo 1 quella di test
```yml
- name: Build docker images
        run: |
          docker build -t "gs:prod" -f tests/docker/Dockerfile .
          docker build -t "gs:dev" --build-arg BASE_IMAGE=gs:prod -f tests/docker/DockerfileDev .
          docker build -t "gs:test" --build-arg BASE_IMAGE=gs:dev -f tests/docker/DockerfileTest .
- name: Run behat
  run: docker run --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 gs:test tests/docker/test-behat.sh ${{ matrix.feature }}
```

questi 2 comandi di build si potrebbero eliminare dal job per ridurne il tempo. 
```yml
          docker build -t "gs:prod" -f tests/docker/Dockerfile .
          docker build -t "gs:dev" --build-arg BASE_IMAGE=gs:prod -f tests/docker/DockerfileDev .
```
@trinko  invio una PR?
